### ISSUE TITLE
Hi, I like this nice and concise template so much! I would appreciate it if you don't mind me to folk and use it as my page.

### ISSUE THREAD

**Issue by liyucheng09** [RulinShao/RulinShao.github.io#1]
rt

**Comment by RulinShao** [comment]
For sure, please feel free to use it :). I copied it from my friend and my friend copied from others lol. I believe [this](https://jonbarron.info/) could potentially be the source.

**Comment by liyucheng09** [comment]
Many thanks! It's funny that [this man](https://jonbarron.info/)'s most starred repo is his webpage template :P
